name = "MPSTime"
uuid = "add04bee-8693-446b-8579-2d5929eca8f6"
authors = ["Joshua Moore <joshua.moore@sydney.edu.au", "Hugo Stackhouse <hugo.stackhouse@sydney.edu.au>"]
version = "0.1.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
NDTensors = "23ae76d9-e61a-49c4-8f12-3f1a16adf9cf"
Normalization = "be38d6a3-8366-4a42-ad57-222272b5bbe7"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OptimKit = "77e91f04-9b3b-57a6-a776-40b61faaebe0"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Distributed = "1.11.0"
Distributions = "0.25.112"
GenericLinearAlgebra = "0.3.13"
ITensors = "=0.6.22"
Integrals = "4.5.0"
JLD2 = "0.4.53"
KernelDensity = "0.6.9"
LaTeXStrings = "1.4.0"
LegendrePolynomials = "0.4.4"
LinearAlgebra = "1.11.0"
MKL = "0.7.0"
MLBase = "0.9.2"
MLJ = "0.20.7"
MLJBase = "1.7.0"
MLJModelInterface = "1.11.0"
NDTensors = "0.3.46"
Normalization = "0.7.2"
NumericalIntegration = "0.2.0"
Optim = "1.9.4"
OptimKit = "0.3.1"
Optimization = "4.1"
OptimizationOptimJL = "0.4.1"
Plots = "1.40.8"
PrettyTables = "2.4.0"
ProgressMeter = "1.10.2"
QuadGK = "2.11.1"
Random = "1.11.0"
SciMLBase = "2.57.1"
StableRNGs = "1.0.2"
StaticArrays = "1.9.11"
StatsBase = "0.34.3"
StatsPlots = "0.15.7"
Strided = "2.1.1"
Tables = "1.12.0"
julia = "1.11.1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
